apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-l2pn
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0026-tenant/tkrw-pr712-0075-0026-app/devfile-sample-l2pn@sha256:b33396818fb8a4f6e4aba46b38beb6e57c8f693c65612355886ea803731cdbe1
        name: my-nodejs
        resources: {}
status: {}
